/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BusinessHour = IDL.Record({
  'day' : IDL.Text,
  'closeTime' : IDL.Text,
  'openTime' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBusinessHours' : IDL.Func([], [IDL.Vec(BusinessHour)], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BusinessHour = IDL.Record({
    'day' : IDL.Text,
    'closeTime' : IDL.Text,
    'openTime' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getBusinessHours' : IDL.Func([], [IDL.Vec(BusinessHour)], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };